"""
Django settings for myproject project.
Generated by 'django-admin startproject' using Django 5.0.
"""

from pathlib import Path
from datetime import timedelta
import os

BASE_DIR = Path(__file__).resolve().parent.parent

# =========================================================
# CORE SETTINGS
# =========================================================
SECRET_KEY = "django-insecure-v29@=8b4x#cz2#-7328&1fbc)1=hh+&!q55sc@s6*apegn7m0$"
DEBUG = True
ALLOWED_HOSTS = ["127.0.0.1", "localhost"]

# =========================================================
# APPLICATION DEFINITION
# =========================================================
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "rest_framework",
    "rest_framework_simplejwt",
    "corsheaders",

    "myapp",
]

AUTH_USER_MODEL = "myapp.User"

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "myproject.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "myproject.wsgi.application"

# =========================================================
# DATABASE (MySQL)
# =========================================================
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "project_db",
        "USER": "root",
        "PASSWORD": "",
        "HOST": "localhost",
        "PORT": "3306",
        "OPTIONS": {"charset": "utf8mb4"},
    }
}

# =========================================================
# DRF + JWT
# =========================================================
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.AllowAny",
    ),
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=7),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# =========================================================
# CORS / CSRF (React)
# =========================================================
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

# =========================================================
# PASSWORD VALIDATION (YOUR WEBSITE USERS)
# =========================================================
# NOTE: This is for your website users (Owner/Tenant/Admin) password.
# This has NOTHING to do with Gmail App Password.
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator", "OPTIONS": {"min_length": 5}},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# =========================================================
# INTERNATIONALIZATION
# =========================================================
LANGUAGE_CODE = "en-us"
TIME_ZONE = "Asia/Kathmandu"
USE_I18N = True
USE_TZ = True

# =========================================================
# STATIC + MEDIA
# =========================================================
STATIC_URL = "static/"
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# =========================================================
# OTP SETTINGS
# =========================================================
APP_NAME = "Smart Rental House Finder"
REQUIRE_GMAIL_ONLY = True

SIGNUP_OTP_TTL_SECONDS = 600
SIGNUP_OTP_MAX_ATTEMPTS = 5
SIGNUP_OTP_RESEND_WINDOW_SECONDS = 900
SIGNUP_OTP_RESEND_LIMIT = 3

REQUIRE_OTP_ON_EVERY_LOGIN = True

EMAIL_OTP_TTL_SECONDS = 600
EMAIL_OTP_MAX_ATTEMPTS = 5
EMAIL_OTP_RESEND_WINDOW_SECONDS = 900
EMAIL_OTP_RESEND_LIMIT = 3

# =========================================================
# EMAIL SETTINGS (GMAIL SMTP) - FIXED TO AVOID "yourgmail@gmail.com"
# =========================================================
# ✅ KEY FIXES:
# 1) NO placeholder default like "yourgmail@gmail.com"
# 2) Removes spaces from app password automatically
# 3) If env vars missing -> use console backend (OTP prints in terminal)
# 4) DOES NOT crash server on wrong length; instead falls back to console
#    (you can force strict mode if you want)

EMAIL_TIMEOUT = 20

EMAIL_HOST_USER = os.environ.get("shrestharabina446@Gmail.com", "").strip()
raw_pass = os.environ.get("glxa wdqz tykr wbnl", "")
EMAIL_HOST_PASSWORD = "".join(raw_pass.split())  # removes spaces + newlines

# Optional: strict mode (True = crash if missing; False = fallback to console)
STRICT_EMAIL = False

print("[EMAIL DEBUG] EMAIL_HOST_USER =", repr(EMAIL_HOST_USER))
print("[EMAIL DEBUG] EMAIL_HOST_PASSWORD length =", len(EMAIL_HOST_PASSWORD))

USE_GMAIL = bool(EMAIL_HOST_USER and EMAIL_HOST_PASSWORD)

if USE_GMAIL:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = "smtp.gmail.com"
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

    # ✅ If you want to allow any length for EMAIL_HOST_PASSWORD, DO NOTHING here.
    # Gmail App Password is normally 16 characters, but we won't hard-fail.
    # If it’s wrong, Gmail will raise 535 and your API will return an error message.

else:
    if STRICT_EMAIL:
        raise RuntimeError(
            "EMAIL_HOST_USER / EMAIL_HOST_PASSWORD missing.\n"
            "Fix (Windows CMD):\n"
            "  set EMAIL_HOST_USER=yourgmail@gmail.com\n"
            "  set EMAIL_HOST_PASSWORD=your_app_password\n"
            "Then restart: python manage.py runserver\n"
        )

    # ✅ Dev fallback: OTP will print in the terminal instead of sending email
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
    DEFAULT_FROM_EMAIL = "no-reply@localhost"

# =========================================================
# LOGGING
# =========================================================
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {"console": {"class": "logging.StreamHandler"}},
    "root": {"handlers": ["console"], "level": "INFO"},
    "loggers": {
        "django": {"handlers": ["console"], "level": "INFO", "propagate": True},
        "django.request": {"handlers": ["console"], "level": "ERROR", "propagate": True},
    },
}
