# Generated by Django 5.0 on 2026-01-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='electricity_bill',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='pano_back',
            field=models.ImageField(blank=True, null=True, upload_to='listings/360/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='pano_down',
            field=models.ImageField(blank=True, null=True, upload_to='listings/360/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='pano_front',
            field=models.ImageField(blank=True, null=True, upload_to='listings/360/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='pano_left',
            field=models.ImageField(blank=True, null=True, upload_to='listings/360/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='pano_right',
            field=models.ImageField(blank=True, null=True, upload_to='listings/360/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='pano_up',
            field=models.ImageField(blank=True, null=True, upload_to='listings/360/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='owner_contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='listing',
            name='owner_contact_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
