# Generated by Django 5.0 on 2025-12-29 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='OwnerProfile',
        ),
        migrations.DeleteModel(
            name='TenantProfile',
        ),
    ]
