# Generated by Django 5.0 on 2026-01-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_listing_electricity_bill_listing_pano_back_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='pano_360',
            field=models.ImageField(blank=True, null=True, upload_to='listings/pano360/'),
        ),
    ]
