# Generated by Django 5.0 on 2026-02-05 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_pendingsignup_pendingsignupotp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='price_per_week',
            new_name='price_per_month',
        ),
        migrations.DeleteModel(
            name='EmailOTP',
        ),
    ]
