# Generated by Django 5.0 on 2026-02-06 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_listingfacility_maintenancerequest_notification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='cleanliness',
        ),
        migrations.RemoveField(
            model_name='review',
            name='neighborhood_safety',
        ),
        migrations.RemoveField(
            model_name='review',
            name='owner_behavior',
        ),
        migrations.RemoveField(
            model_name='review',
            name='water',
        ),
        migrations.AlterField(
            model_name='review',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_written', to=settings.AUTH_USER_MODEL),
        ),
    ]
