# Generated by Django 5.0 on 2026-02-24 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_maintenancerequest_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='address',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='address',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='phone',
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='assigned_provider',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'provider'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='category',
            field=models.CharField(choices=[('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('cleaning', 'Cleaning'), ('internet', 'Internet/WiFi'), ('gas', 'Gas'), ('hvac', 'AC / Heating'), ('pest_control', 'Pest Control'), ('carpentry', 'Carpentry'), ('painting', 'Painting'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_requests', to='myapp.listing'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_maintenance_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='owner',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='serviceproviderprofile',
            name='category',
            field=models.CharField(choices=[('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('cleaning', 'Cleaning'), ('internet', 'Internet/WiFi'), ('gas', 'Gas'), ('hvac', 'AC / Heating'), ('pest_control', 'Pest Control'), ('carpentry', 'Carpentry'), ('painting', 'Painting'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('listing', 'tenant'), name='uniq_review_listing_tenant'),
        ),
        migrations.AddField(
            model_name='providermessage',
            name='maintenance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='myapp.maintenancerequest'),
        ),
        migrations.AddField(
            model_name='providermessage',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_messages_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='providermessage',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_messages_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='providermessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_messages_as_sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='providermessage',
            index=models.Index(fields=['provider', '-created_at'], name='myapp_provi_provide_309519_idx'),
        ),
        migrations.AddIndex(
            model_name='providermessage',
            index=models.Index(fields=['owner', '-created_at'], name='myapp_provi_owner_i_d7f39c_idx'),
        ),
    ]
