# Generated by Django 5.0 on 2026-03-01 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_providermessage_alter_review_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoommateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('any', 'Any')], default='any', max_length=10)),
                ('preferred_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('any', 'Any')], default='any', max_length=10)),
                ('min_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('preferred_area', models.CharField(blank=True, default='', max_length=120)),
                ('move_in_date', models.DateField(blank=True, null=True)),
                ('stay_length_months', models.IntegerField(blank=True, null=True)),
                ('smoker', models.BooleanField(default=False)),
                ('pets_ok', models.BooleanField(default=True)),
                ('tidy_level', models.IntegerField(default=3)),
                ('quiet_level', models.IntegerField(default=3)),
                ('bio', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roommate_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoommateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roommate_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roommate_requests_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('from_user', 'to_user')},
            },
        ),
    ]
