# Generated by Django 5.0 on 2026-03-08 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_roommatechatthread_roommatechatmessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FurnitureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('Sofa', 'Sofa'), ('Bed', 'Bed'), ('Chair', 'Chair'), ('Table', 'Table'), ('Lamp', 'Lamp'), ('Plant', 'Plant'), ('Cabinet', 'Cabinet'), ('Other', 'Other')], default='Other', max_length=50)),
                ('furniture_type', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to='furniture/')),
                ('width', models.PositiveIntegerField(default=120)),
                ('height', models.PositiveIntegerField(default=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
