# Generated by Django 5.0 on 2026-03-14 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_furnitureitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPaymentQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Main Payment QR', max_length=100)),
                ('qr_image', models.ImageField(upload_to='payment_qr/')),
                ('account_name', models.CharField(blank=True, max_length=120)),
                ('provider_name', models.CharField(blank=True, max_length=120)),
                ('account_number', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_qrs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_month', models.CharField(max_length=50)),
                ('payment_date', models.DateField()),
                ('transaction_id', models.CharField(blank=True, max_length=120)),
                ('screenshot', models.ImageField(upload_to='rent_payment_proofs/')),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_remark', models.TextField(blank=True)),
                ('owner_payout_status', models.CharField(choices=[('not_paid', 'Not Paid'), ('paid', 'Paid')], default='not_paid', max_length=20)),
                ('owner_payout_date', models.DateField(blank=True, null=True)),
                ('owner_payout_note', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_payments', to='myapp.listing')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_rent_payments', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_rent_payments', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
