# Generated by Django 5.0 on 2026-03-15 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_adminpaymentqr_rentpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('admin_share_percent', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('owner_share_percent', models.DecimalField(decimal_places=2, default=80.0, max_digits=5)),
                ('admin_share_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('owner_share_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transaction_uuid', models.CharField(max_length=100, unique=True)),
                ('product_code', models.CharField(default='EPAYTEST', max_length=50)),
                ('ref_id', models.CharField(blank=True, max_length=120, null=True)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled'), ('NOT_FOUND', 'Not Found'), ('AMBIGUOUS', 'Ambiguous'), ('FULL_REFUND', 'Full Refund'), ('PARTIAL_REFUND', 'Partial Refund')], default='PENDING', max_length=20)),
                ('owner_payout_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('owner_payout_date', models.DateTimeField(blank=True, null=True)),
                ('owner_payout_note', models.TextField(blank=True)),
                ('payment_month', models.CharField(blank=True, max_length=50)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_payments', to='myapp.listing')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_payments_as_owner', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_payments_as_tenant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
