# Generated by Django 5.0 on 2026-03-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_bookingpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentpayment',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='rentpayment',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='rentpayment',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='rentpayment',
            name='verified_by',
        ),
        migrations.AddField(
            model_name='bookingpayment',
            name='is_first_property_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='AdminPaymentQR',
        ),
        migrations.DeleteModel(
            name='RentPayment',
        ),
    ]
