# Generated by Django 5.0 on 2026-03-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_remove_rentpayment_listing_remove_rentpayment_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/booking/'),
        ),
        migrations.AddField(
            model_name='providermessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/provider/'),
        ),
        migrations.AddField(
            model_name='roommatechatmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/roommate/'),
        ),
    ]
