# Generated by Django 5.0 on 2026-04-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_tenantroomimagesave_delete_virtualfurnituredesign'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantroomimagesave',
            name='layout_data',
            field=models.TextField(blank=True, help_text='JSON data containing furniture layout information', null=True),
        ),
    ]
