# Generated by Django 5.0 on 2026-04-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_tenantroomimagesave_layout_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommatechatmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
