# Generated by Django 5.0 on 2026-04-14 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_title', models.CharField(blank=True, max_length=255)),
                ('rent_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_due_day', models.PositiveIntegerField(default=5)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('utility_terms', models.TextField(blank=True, default='')),
                ('house_rules', models.TextField(blank=True, default='')),
                ('special_terms', models.TextField(blank=True, default='')),
                ('generated_text', models.TextField(blank=True, default='')),
                ('owner_signed', models.BooleanField(default=False)),
                ('tenant_signed', models.BooleanField(default=False)),
                ('owner_signed_at', models.DateTimeField(blank=True, null=True)),
                ('tenant_signed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_tenant', 'Pending Tenant'), ('pending_owner', 'Pending Owner'), ('active', 'Active'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='myapp.bookingrequest')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='myapp.listing')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_contracts', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_contracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
