# Generated by Django 5.0 on 2026-04-15 07:03

import django.db.models.deletion
import myapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_rentalcontract'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerPlatformAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_key', models.CharField(default='property_listing_v1', max_length=100)),
                ('agreement_title', models.CharField(default='Property Listing Agreement', max_length=255)),
                ('agreement_version', models.CharField(default='v1', max_length=50)),
                ('agreement_text', models.TextField(default=myapp.models.default_owner_agreement_text)),
                ('platform_first_payment_percent', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('owner_first_payment_percent', models.DecimalField(decimal_places=2, default=80.0, max_digits=5)),
                ('future_payment_owner_percent', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='platform_agreement', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
