# Generated by Django 5.0 on 2026-04-18 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_ownerplatformagreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='property_type',
            field=models.CharField(choices=[('room', 'Room'), ('flat', 'Flat'), ('house', 'House'), ('apartment', 'Apartment')], default='room', max_length=20),
        ),
        migrations.CreateModel(
            name='PropertyGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/gallery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='myapp.listing')),
            ],
        ),
    ]
